#ifndef dice_tui_err_h
#define dice_tui_err_h
typedef enum {
    DICE_TUI_SUCCESS = 0,
    DICE_TUI_ERR_OUT_OF_BOUNDS,
    DICE_TUI_ERR_BUFFER_OVERFLOW,
    DICE_TUI_ERR_MALLOC_FAILED,
    DICE_TUI_ERR_NULL_POINTER,
    DICE_TUI_ERR_TERMINAL_NOT_TTY,
    DICE_TUI_ERR_RAW_MODE_FAILED,
    DICE_TUI_ERR_SCREEN_TOO_SMALL,
    DICE_TUI_ERR_COORDINATE_NEGATIVE,
    DICE_TUI_ERR_IO_FAILED,
    DICE_TUI_ERR_UNKNOWN
} dice_tui_status_t;
#endif
